sudo: required
services:
  - docker

before_install:
  - docker build -t vverma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vverma/react-test npm test -- --coverage

after_success:
  - docker build -t vverma/multi-client ./client
  - docker build -t vverma/multi-nginx ./nginx
  - docker build -t vverma/multi-server ./server
  - docker build -t vverma/multi-worker ./worker
# Login in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to dockerHub
  - docker push vverma/multi-client
  - docker push vverma/multi-nginx
  - docker push vverma/multi-server
  - docker push vverma/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-795735340981
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
