sudo: required
services:
  - docker

before_install:
  - docker build -t vverma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vverma/react-test npm test -- --coverage

after_success:
  - docker build -t vverma/multi-client ./client
  - docker build -t vverma/multi-nginx ./nginx
  - docker build -t vverma/multi-server ./server
  - docker build -t vverma/multi-worker ./worker
# Login in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to dockerHub
  - docker push vverma/multi-client
  - docker push vverma/multi-nginx
  - docker push vverma/multi-server
  - docker push vverma/multi-worker
